name: Build App

on:
  push:
    branches:
      - master
      
jobs:
  build:
    
    name: Compilación de la App
    runs-on: ubuntu-latest
    steps:
      - name: Colocamos acciones del marketplace
        uses: actions/checkout@v2
      - name: ¿Dónde estoy?
        run: ls
      - name: Build con dotnet
        run: dotnet build
        

